"""empty message

Revision ID: 78356d2d9bb7
Revises: 
Create Date: 2017-01-28 20:34:25.909936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78356d2d9bb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('date_period', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('number_rooms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number_rooms')
    op.drop_column('users', 'date_period')
    op.drop_column('users', 'city')
    op.drop_column('users', 'budget')
    # ### end Alembic commands ###
